# Generated by Django 4.2.1 on 2023-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducts',
            name='reference',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
