# Generated by Django 4.2.1 on 2023-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_historicalproducts_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
